name: Test OpenAI Function Calling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v3

    - name: Python のセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: 依存関係のインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: テストスクリプトの実行
      run: pytest test_main.py
